# Generated by Django 3.2.21 on 2023-10-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spotify_sample_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Spotify Sample URL'),
        ),
    ]
